default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: <%= ENV['DATABASE_HOST'] || '127.0.0.1' %>
  port: 5432

development:
  <<: *default
  database: rails-kube-demo_development

test:
  <<: *default
  database: rails-kube-demo_test

production:
  <<: *default
  database: app_production
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>